let dados = [
    {   
        localimagem: "style='float:left; margin-right: 10px;' class='imagem-ajustada'",
        alt: "Símbolo Neurodiversidade",
        imagem: "imagens/neurodiversidade.png", 
        titulo: "O que é Neurodiversidade?",
        descricao: "Neurodiversidade é o termo usado para descrever a variedade de composições neurológicas que existem entre os seres humanos. A ideia é que a mente pode funcionar de diferentes formas, e que essas diferenças são variações naturais do cérebro, e não doenças ou incapacidades. O termo foi criado em 1999 pela socióloga australiana Judy Singer, que costumava comparar a neurodiversidade à biodiversidade.",
        link: "https://www.vittude.com/blog/neurodiversidade/",
        youtube: "https://www.youtube.com/watch?v=wnnNF-xMlIA",
        tags: "neurodivergente",
    },
    {  
        localimagem: "style='float:right; margin-right: 10px;' class='imagem-ajustada'",
        imagem: "imagens/autismo.png",
        titulo: "Transtorno do Espectro Autista - TEA",
        descricao: "O TEA, ou Transtorno do Espectro Autista, é uma condição que afeta o neurodesenvolvimento, caracterizada por dificuldades na comunicação, interação social e comportamentos repetitivos, manifestando-se de forma única em cada indivíduo.",
        link: "https://www.tuasaude.com/autismo-infantil/",
        youtube: "https://www.youtube.com/watch?v=8uTHFYAQtnA",
        tags: "autista condição social interação",
    },
    {
        localimagem: "style='float:left; margin-right: 10px;' class='imagem-ajustada'",
        imagem: "imagens/adhd.png",
        titulo: "Transtorno do Déficit de Atenção e Hiperatividade - TDAH",
        descricao: "O TDAH é um transtorno neurobiológico caracterizado por desatenção, hiperatividade e impulsividade, afetando a capacidade de se concentrar, controlar impulsos e permanecer quieto.",
        link: "https://drauziovarella.uol.com.br/pediatria/tdah-transtorno-do-deficit-de-atencao-com-hiperatividade/",
        youtube: "https://www.youtube.com/watch?v=8NK6rmZscWU",
        tags: "tdah hiperativo deficit impulso",
    },
    {   
        localimagem: "style='float:right; margin-right: 10px;' class='imagem-ajustada'",
        imagem: "imagens/dispraxia.png",
        titulo: "Dispraxia",
        descricao: " A dispraxia é um transtorno neurológico que dificulta a coordenação de movimentos, afetando a capacidade de planejar e executar ações motoras, como andar, escrever ou falar. Em termos mais simples, é uma condição que faz com que o cérebro tenha dificuldade em 'mandar' o corpo realizar tarefas de forma coordenada.",
        link: "https://drauziovarella.uol.com.br/neurologia/dispraxia-um-disturbio-infantil-que-pode-passar-despercebido/",
        youtube: "https://www.youtube.com/watch?v=Woy8wF2ud1I",
        tags: "coordenação motora capacidade",
    },
    {   
        localimagem: "style='float:left; margin-right: 10px;' class='imagem-ajustada'",
        imagem: "imagens/dislexia.png",
        titulo: "Dislexia",
        descricao: "A dislexia é um transtorno de aprendizagem que dificulta a leitura e a escrita, mesmo com inteligência normal, devido a dificuldades na decodificação e na soletração das palavras.",
        link: "https://www.dislexia.org.br/o-que-e-dislexia/",
        youtube: "https://www.youtube.com/watch?v=tV9OvfX7rlw",
        tags: "palavras escrever escrita aprendizagem ",
    },
    {   localimagem: "style='float:right; margin-right: 10px;' class='imagem-ajustada'",
        imagem: "imagens/tourette.png",
        titulo: "Síndrome de Tourette",
        descricao: " A síndrome de Tourette é um transtorno neurológico caracterizado por movimentos involuntários repetitivos e rápidos, tanto motores quanto vocais, conhecidos como tiques.",
        link: "https://drauziovarella.uol.com.br/pediatria/sindrome-de-tourette/",
        youtube: "https://www.youtube.com/watch?v=ZYAfjjHrI_A",
        tags: "tourete palavrao tique motor vocal vocais",
    },
];